### ISSUE TITLE
Bar chart crash when yMaxValue = 0

### ISSUE THREAD

**Issue by leoreisbk** [kevinzhow/PNChart-Swift#26]
var grade = value / yValueMax.

I want to show negative values in a bar chart, how can i do it?

**Comment by sudeepag** [comment]
Is there any fix to this? Getting the same error.

**Comment by gbmksquare** [comment]
You can prevent crashing by adding `barChart.yMinValue = -10` when initiazliaing. But it doesn't seem to show minus value in downward direction.
