### ISSUE TITLE
PNChart-Swift Licence

### ISSUE THREAD

**Issue by outsideride** [kevinzhow/PNChart-Swift#28]
Hi Kevin,

Noticed the PNChart-Swift repo doesn't include a license like the Objective C version does.  Is it licensed under MIT license as well?  Can you post the license right in the Swift repo?

Regards,
OutsideRide

**Comment by kevinzhow** [comment]
Under MIT license as well, but Swift version is not full-featured. Please use objc version instead.

**Comment by outsideride** [comment]
Thanks Kevin, and good work!
