### ISSUE TITLE
show Y labels in bar chart

### ISSUE THREAD

**Issue by acroventus** [kevinzhow/PNChart-Swift#31]
Hi! I'm using the demo app that's included on the repository but I'm having troubles showing the YLabels on the Bar Chart. The values are shown but they're all 0. Here's the code: 
![captura de pantalla 2015-02-23 a las 15 31 59](https://cloud.githubusercontent.com/assets/10597926/6334117/39dc6378-bb71-11e4-969c-36938c30580d.png)

**Comment by lamfete** [comment]
Hi, try this. It's work for me

![screen shot 2015-02-24 at 10 37 54 am](https://cloud.githubusercontent.com/assets/6195369/6342815/4dc21af4-bc11-11e4-88e3-3b5cf2106f19.png)

**Comment by opswhisperer** [comment]
I don't see that yLabelFormatter exists anymore . . . is there an alternative?

**Comment by opswhisperer** [comment]
in the obj-c version I could just do this
//barChart.yLabels = Array(0.stride(through: values.maxElement()!, by: 1))

no such luck here. I think whoever started porting this to Swift must have given up
