### ISSUE TITLE
Can't running in my Xcode 6.2 :-(

### ISSUE THREAD

**Issue by lmcmz** [kevinzhow/PNChart-Swift#35]
我也是国人，打开来发下 70多个 issues 求解，新手不太懂。

**Comment by kevinzhow** [comment]
Swift version is under development, May use Xcode 6.3

**Comment by lmcmz** [comment]
I tried the Xcode 6.3 but It seem there are still 3 issues .  :(
![2015-03-17 4 12 19](https://cloud.githubusercontent.com/assets/9669733/6698682/6f673404-ccc0-11e4-86c4-0251d3fe3fbd.png)

**Comment by kevinzhow** [comment]
Have you run pod install?

**Comment by lmcmz** [comment]
No, I'm a beginner in iOS with swift.
:-(
Sorry I have no idea how to code in Obj-C to test your code.
And I just found the PNChart in Swift not exist in cocoPods.
It seem there just have obj-c version.
Recently I'm doing a project for practice.
I do really need your code to analysis those datas.

By the way, thanks so much to reply a noob.
I know maybe my question is a kind of low-grade.
But It do really confuse me. :(

![2015-03-17 8 04 25](https://cloud.githubusercontent.com/assets/9669733/6701306/d9515a28-cce0-11e4-81d9-65747d6282f1.png)

**Comment by kevinzhow** [comment]
pod install will install the dependency, not for the PNChart.
Also you can try Objc version. 0.8.2 supports interaction with Swift.

**Comment by lmcmz** [comment]
Yeah , it seem I misunderstand your words.
So you mean I have to use Terminal ( 'pod install' ) to install the dependency to the ExampleApp?

**Comment by lmcmz** [comment]
Thanks so much.
I figure it out.
It work well in your obj-c version but in swift version.
I met a warning in Terminal and I change  to use framework.
It worked but no answer in CircleChart and PieChart table cell.
![2015-03-17 8 18 07](https://cloud.githubusercontent.com/assets/9669733/6701648/60861c28-cce5-11e4-9627-d39992e343ff.png)
![2015-03-17 8 35 23](https://cloud.githubusercontent.com/assets/9669733/6701659/74a1617c-cce5-11e4-86e0-29e0fdaf6265.png)

**Comment by kevinzhow** [comment]
Swift Version is ready for production usage.
Please try objc version

**Comment by lmcmz** [comment]
Would you please pull the swift version in cocosPods ?
I try the Object-C version but It seem some of the functions are different.
For example: swift have the animationType.
I'm sorry to bother you.
But I just need the BarChart.I knew the other functions didn't finish.
By the way , is there anyway else to integrate your code in my project without using cocosPod?
Thanks so much.

**Comment by ahan** [comment]
I'm sorry, I see your last reply, "Swift Version is ready for production usage."

is not ready? or is ready?

**Comment by kevinzhow** [comment]
Not ready
