### ISSUE TITLE
labels density

### ISSUE THREAD

**Issue by eriktelepovsky** [kevinzhow/PNChart-Swift#38]
Hi, first of all, thanks for library! 
I try to figure out how to set line chart to show labels correctly if there are many same values. 

For example:

```swift
lineChart.xLabels = [
            "27.3","28.3","29.3","30.3","31.3","1.","2.",
            "3.","4.","5.","6.","7.","8.","9.",
            "10.","11.","12.","13.","14.","15.","16.",
            "17.","18.","19.","20.","21.","22.","23.",
            "23.","24."
        ]

var data01Array: [CGFloat] = [
            2, 4, 5, 3, 5, 2, 3,
            1, 4, 2, 0, 5, 6, 4,
            3, 4, 2, 1, 5, 0, 3,
            2, 5, 4, 1, 3, 2, 4,
            1, 5
        ]
```

produces line chart with same y labels with overflow:

![labels](https://cloud.githubusercontent.com/assets/2685808/7350551/2c35a714-ed00-11e4-86a6-5d1f844b37ed.PNG)

There should be only 7 y labels 0, 1, 2, 3, 4, 5, 6.

Thanks for help.

**Comment by kevinzhow** [comment]
Swift version is not quite usable, please use the objc version

**Comment by eriktelepovsky** [comment]
All right. Thank you.
