### ISSUE TITLE
Cocoapods install error

### ISSUE THREAD

**Issue by dongkaipo** [kevinzhow/PNChart-Swift#47]
Unable to find a specification for `PNChartSwift`

**Comment by bradddd** [comment]
It's not on Cocoapods yet, so put this in your Podfile instead to install from the github repo:
```
pod 'PNChartSwift',:git => 'https://github.com/kevinzhow/PNChart-Swift.git'
```

**Comment by sleepwalkerfx** [comment]
Still this doesn't work.

**Comment by lenkaiser** [comment]
Please have a look at: https://github.com/kevinzhow/PNChart-Swift/issues/73

**Comment by Bijiabo** [comment]
Still this doesn't work. +1

**Comment by stephen-talari** [comment]
Having the same issue,
It was working with someone else's fork
`pod 'PNChartSwift', :git => 'https://github.com/lenkaiser/PNChart-Swift'`

Any fix in this repo?
