### ISSUE TITLE
Auto layout support.

### ISSUE THREAD

**Issue by gbmksquare** [kevinzhow/PNChart-Swift#56]
Needs automatically re-render chart when layout has changed.

**Comment by hansemannn** [comment]
@gbmksquare Did you find a workaround to manually apply autolayout constraints? I'm wondering if we could just set superview-bounds to the constraints and go from there.

**Comment by gbmksquare** [comment]
@hansemannn For now I just remove and re-add chart view in `traitCollectionDidChange(previousTraitCollection:)`
