### ISSUE TITLE
Unable to run the ExampleApp

### ISSUE THREAD

**Issue by MariamNers** [kevinzhow/PNChart-Swift#57]
Hi! I am trying to run the example app but i am getting this error:

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I understand i need to install cocoa pods, but i am unclear as to why if i am using swift?

**Comment by stephen-talari** [comment]
Yes, build fails for me too with same error

**Comment by dqhieu** [comment]
You need to run 'pod install' first
